server:
  port: 9300

spring:
  config:
    import: "configserver:http://localhost:9002/"

  datasource:
    url: jdbc:mysql://localhost:3306/mdd_article?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: mdd_article_access
    password: X$qaxOnxcjyctyZGqm1Kfn2#aQsF$G
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    public-key: classpath:jwt/public.pem
