server:
  port: 9200

spring:
  config:
    import: "configserver:http://localhost:9002/"

  datasource:
    url: jdbc:mysql://localhost:3306/mdd_theme?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: mdd_theme_access
    password: j#QHK8KxxchTPxiuyU7SUxMXI&Ax?I
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    public-key: classpath:jwt/public.pem
