server:
  port: 9100

spring:
  config:
    import: "configserver:http://localhost:9002/"

  datasource:
    url: jdbc:mysql://localhost:3306/mdd_user?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: mdd_user_access
    password: BSa8brppPVxTmZRNzHm0$0rxAq8Qx6
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    private-key: classpath:jwt/private-pkcs8.pem
    public-key: classpath:jwt/public.pem
    issuer: self
    expires-in: 3600
